name: CI

on:
  push:
    branches: [ '**' ]
  pull_request:
    branches: [ '**' ]

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: '-D warnings'

jobs:
  cackle:
    name: Cackle check and test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
      - run: sudo apt-get update && sudo apt-get install bubblewrap
      - run: cargo build --release
      - run: cp target/release/cargo-acl .
      - run: pwd >> $GITHUB_PATH
      - run: cargo acl -n
      - run: cargo acl -n test
